def tomcatWeb = 'C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps'

job('job-dsl-checkout') {
    
    scm {
        github('Harshahrs/Demo', 'master')
    }
      
   publishers {
        downstream 'job-dsl-compile', 'SUCCESS'
    }
    
}


mavenJob('job-dsl-compile'){
   
  customWorkspace('C:/Users/Harsha/AppData/Local/Jenkins/.jenkins/workspace/job-dsl-checkout/demojenkins')
  mavenInstallation('Maven 3.3.9')
  goals('compile')
    
  publishers {
        downstream 'job-dsl-package', 'SUCCESS'
   }
}


mavenJob('job-dsl-package'){
scm{
  customWorkspace('C:/Users/Harsha/AppData/Local/Jenkins/.jenkins/workspace/job-dsl-checkout/demoJenkins')
  }    
  mavenInstallation('Maven 3.3.9')
    goals('package')
    
  publishers {
        downstream 'job-dsl-deploy', 'SUCCESS'
  }
}


job('job-dsl-deploy') {
    description 'Deploy app to the demo server'
    
    steps{
             shell 'sshpass -p "123456" scp C:/Users/Harsha/AppData/Local/Jenkins/.jenkins/workspace/job-dsl-checkout/demoJenkins/target/demoJenkins.war \"${tomcatWeb}\\demoJenkins.war\"'
      }
}


listView('List View DSLs') {
    jobs {
        regex('job-dsl-.+')
    }
    columns {
        status()
        name()
        lastSuccess()
        lastFailure()
        lastDuration()
        buildButton()
    }
}


deliveryPipelineView('job-dsl delivery pipeline') {
    showAggregatedPipeline true
    enableManualTriggers true
    pipelineInstances 5
    pipelines {
        component('job-dsl delivery pipeline', 'job-dsl-checkout')
    }
}
